//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoService.ServiceBaseSINAF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceBaseSINAF.SyncSINAFSoap")]
    public interface SyncSINAFSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterPrimeiroServico", ReplyAction="*")]
        int ObterPrimeiroServico();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportarBancoCorreio", ReplyAction="*")]
        bool ImportarBancoCorreio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportarBaseSINAF", ReplyAction="*")]
        bool ImportarBaseSINAF();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface SyncSINAFSoapChannel : ProjetoService.ServiceBaseSINAF.SyncSINAFSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SyncSINAFSoapClient : System.ServiceModel.ClientBase<ProjetoService.ServiceBaseSINAF.SyncSINAFSoap>, ProjetoService.ServiceBaseSINAF.SyncSINAFSoap {
        
        public SyncSINAFSoapClient() {
        }
        
        public SyncSINAFSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SyncSINAFSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SyncSINAFSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SyncSINAFSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ObterPrimeiroServico() {
            return base.Channel.ObterPrimeiroServico();
        }
        
        public bool ImportarBancoCorreio() {
            return base.Channel.ImportarBancoCorreio();
        }
        
        public bool ImportarBaseSINAF() {
            return base.Channel.ImportarBaseSINAF();
        }
    }
}
