//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3655
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.3655.
// 
namespace ProjetoMobile.wsColetor {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SyncColetorSoap", Namespace="http://tempuri.org/")]
    public partial class SyncColetor : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public SyncColetor() {
            this.Url = "http://sql-cabtec/SINAF/Service/SyncColetor.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetDateTime", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime SetDateTime() {
            object[] results = this.Invoke("SetDateTime", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetDateTime(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetDateTime", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.DateTime EndSetDateTime(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerSenhaHash", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VerSenhaHash(string password) {
            object[] results = this.Invoke("VerSenhaHash", new object[] {
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginVerSenhaHash(string password, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("VerSenhaHash", new object[] {
                        password}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndVerSenhaHash(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerificaColetorAtivo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool VerificaColetorAtivo(string numeroSerie) {
            object[] results = this.Invoke("VerificaColetorAtivo", new object[] {
                        numeroSerie});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginVerificaColetorAtivo(string numeroSerie, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("VerificaColetorAtivo", new object[] {
                        numeroSerie}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndVerificaColetorAtivo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ImportarBancoCorreios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ImportarBancoCorreios(string numeroSerie, string siglaUF, int versaoAtual, out int versaoNova) {
            object[] results = this.Invoke("ImportarBancoCorreios", new object[] {
                        numeroSerie,
                        siglaUF,
                        versaoAtual});
            versaoNova = ((int)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginImportarBancoCorreios(string numeroSerie, string siglaUF, int versaoAtual, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ImportarBancoCorreios", new object[] {
                        numeroSerie,
                        siglaUF,
                        versaoAtual}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndImportarBancoCorreios(System.IAsyncResult asyncResult, out int versaoNova) {
            object[] results = this.EndInvoke(asyncResult);
            versaoNova = ((int)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ImportarBancoCorreiosTeste", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ImportarBancoCorreiosTeste(string numeroSerie, string siglaUF, int versaoAtual) {
            object[] results = this.Invoke("ImportarBancoCorreiosTeste", new object[] {
                        numeroSerie,
                        siglaUF,
                        versaoAtual});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginImportarBancoCorreiosTeste(string numeroSerie, string siglaUF, int versaoAtual, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ImportarBancoCorreiosTeste", new object[] {
                        numeroSerie,
                        siglaUF,
                        versaoAtual}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndImportarBancoCorreiosTeste(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ImportarBanco", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ImportarBanco(string numeroSerie, string versao, out int numeroDownload) {
            object[] results = this.Invoke("ImportarBanco", new object[] {
                        numeroSerie,
                        versao});
            numeroDownload = ((int)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginImportarBanco(string numeroSerie, string versao, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ImportarBanco", new object[] {
                        numeroSerie,
                        versao}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndImportarBanco(System.IAsyncResult asyncResult, out int numeroDownload) {
            object[] results = this.EndInvoke(asyncResult);
            numeroDownload = ((int)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExportarBanco", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ExportarBanco(string numeroSerie, string versao, out int numeroUpload) {
            object[] results = this.Invoke("ExportarBanco", new object[] {
                        numeroSerie,
                        versao});
            numeroUpload = ((int)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginExportarBanco(string numeroSerie, string versao, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ExportarBanco", new object[] {
                        numeroSerie,
                        versao}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndExportarBanco(System.IAsyncResult asyncResult, out int numeroUpload) {
            object[] results = this.EndInvoke(asyncResult);
            numeroUpload = ((int)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ImportarBancoTeste", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ImportarBancoTeste(string numeroSerie, string versao) {
            object[] results = this.Invoke("ImportarBancoTeste", new object[] {
                        numeroSerie,
                        versao});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginImportarBancoTeste(string numeroSerie, string versao, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ImportarBancoTeste", new object[] {
                        numeroSerie,
                        versao}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndImportarBancoTeste(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExportarBancoTeste", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ExportarBancoTeste(string numeroSerie, string versao) {
            object[] results = this.Invoke("ExportarBancoTeste", new object[] {
                        numeroSerie,
                        versao});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginExportarBancoTeste(string numeroSerie, string versao, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ExportarBancoTeste", new object[] {
                        numeroSerie,
                        versao}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndExportarBancoTeste(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExcluirBackupColetor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ExcluirBackupColetor() {
            object[] results = this.Invoke("ExcluirBackupColetor", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginExcluirBackupColetor(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ExcluirBackupColetor", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndExcluirBackupColetor(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerificarAtualizacaoDisponivel", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VerificarAtualizacaoDisponivel(string coletor) {
            object[] results = this.Invoke("VerificarAtualizacaoDisponivel", new object[] {
                        coletor});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginVerificarAtualizacaoDisponivel(string coletor, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("VerificarAtualizacaoDisponivel", new object[] {
                        coletor}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndVerificarAtualizacaoDisponivel(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
